
[tool.poetry]
name = "summarize-anthropic"
version = "0.1.0"
description = "This template uses Anthropic's `Claude2` to summarize long documents."
authors = ["Lance Martin <lance@langchain.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
gigachain = ">=0.0.325"
anthropic = ">=0.5.0"
langchainhub = ">=0.1.13"
langchain-anthropic = "^0.1.4"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.templates-hub]
use-case = "summarization"
author = "LangChain"
integrations = ["Anthropic"]
tags = ["summarization"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

