<<<<<<< HEAD

=======
>>>>>>> langchan/master
[tool.poetry]
name = "summarize-anthropic"
version = "0.1.0"
description = "This template uses Anthropic's `Claude2` to summarize long documents."
authors = ["Lance Martin <lance@langchain.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
<<<<<<< HEAD
gigachain = "^0.1"
langchainhub = ">=0.1.13"
gigachain-anthropic = "^0.1.4"

[tool.poetry.group.dev.dependencies]
gigachain-cli = ">=0.0.21"
=======
langchain = "^0.1"
langchainhub = ">=0.1.13"
langchain-anthropic = "^0.1.4"

[tool.poetry.group.dev.dependencies]
langchain-cli = ">=0.0.21"

[tool.langserve]
export_module = "summarize_anthropic"
export_attr = "chain"
>>>>>>> langchan/master

[tool.templates-hub]
use-case = "summarization"
author = "LangChain"
integrations = ["Anthropic"]
tags = ["summarization"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
<<<<<<< HEAD

=======
>>>>>>> langchan/master
