<<<<<<< HEAD
name: "\U0001F680 Запрос на функциональность"
description: Отправьте запрос или сделайте предложение по доработке функциональности GigaChain
labels: ["02 "]
=======
labels: [idea]
>>>>>>> langchan/master
body:
  - type: checkboxes
    id: checks
    attributes:
      label: Checked
      description: Please confirm and check all the following options.
      options:
        - label: I searched existing ideas and did not find a similar one
          required: true
        - label: I added a very descriptive title
          required: true
        - label: I've clearly described the feature request and motivation for it
          required: true
  - type: textarea
    id: feature-request
    validations:
      required: true
    attributes:
<<<<<<< HEAD
      label: Описание функциональности
      description: |
        Краткое описание предлагаемых доработок по существу. Приведите ссылки на подходящие GitHub-репозитории, статьи или другие ресурсы.

=======
      label: Feature request
      description: |
        A clear and concise description of the feature proposal. Please provide links to any relevant GitHub repos, papers, or other resources if relevant.
>>>>>>> langchan/master
  - type: textarea
    id: motivation
    validations:
      required: true
    attributes:
<<<<<<< HEAD
      label: Обоснование
      description: |
        Опишите, что побудило вас предложить доработку. Если предложенная функциональность связанна с существующей issue, дайте ссылку на неё.

=======
      label: Motivation
      description: |
        Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too.
>>>>>>> langchan/master
  - type: textarea
    id: proposal
    validations:
      required: false
    attributes:
<<<<<<< HEAD
      label: Ваш вклад
      description: |
        Возможно, вы хотите предложить свое решение и отправить PR? Пожалуйста, ознакомьтесь с правилами создания PR, описанными в [CONTRIBUTING.MD](https://github.com/langchain-ai/langchain/blob/master/.github/CONTRIBUTING.md).
=======
      label: Proposal (If applicable)
      description: |
        If you would like to propose a solution, please describe it here. 
>>>>>>> langchan/master
