<<<<<<< HEAD
name: "\U0001F41B Сообщение об ошибке"
description: Сообщите об ошибке, чтобы улучшить работу GigaChain. Для обратной связи о проблемах с безопасностью воспользуйтесь отдельной формой ниже.
labels: ["02 Сообщение об ошибке"]
=======
name: "\U0001F41B Bug Report"
description: Report a bug in LangChain. To report a security issue, please instead use the security option below. For questions, please use the GitHub Discussions.
labels: ["02 Bug Report"]
>>>>>>> langchan/master
body:
  - type: markdown
    attributes:
      value: >
<<<<<<< HEAD

        Перед тем как сообщить об ошибке, пожалуйста, убедитесь, что вашей проблемы нет среди открытых issue.

  - type: textarea
    id: system-info
    attributes:
      label: Информация об окружении
      description: Расскажите об окружении, в котором возникла ошибка.
      placeholder: Версия GigaChain, версия python, операционная система, ...
    validations:
      required: true
    attributes:
      label: К кому обратиться?
      description: |
        Разработчики стараются своевременно обрабатывать все открытые issue. Тем не менее, если вы считаете, что обнаруженную ошибку нужно рассмотреть с повышенным приоритетом, вы можете уведомить об этом руководителя проекта — @Rai220.
=======
        Thank you for taking the time to file a bug report. 
        
        Use this to report bugs in LangChain. 
        
        If you're not certain that your issue is due to a bug in LangChain, please use [GitHub Discussions](https://github.com/langchain-ai/langchain/discussions)
        to ask for help with your issue.
        
        Relevant links to check before filing a bug report to see if your issue has already been reported, fixed or
        if there's another way to solve your problem:
        
        [LangChain documentation with the integrated search](https://python.langchain.com/docs/get_started/introduction),
        [API Reference](https://api.python.langchain.com/en/stable/),
        [GitHub search](https://github.com/langchain-ai/langchain),
        [LangChain Github Discussions](https://github.com/langchain-ai/langchain/discussions),
        [LangChain Github Issues](https://github.com/langchain-ai/langchain/issues?q=is%3Aissue),
        [LangChain ChatBot](https://chat.langchain.com/)
  - type: checkboxes
    id: checks
    attributes:
      label: Checked other resources
      description: Please confirm and check all the following options.
      options:
        - label: I added a very descriptive title to this issue.
          required: true
        - label: I searched the LangChain documentation with the integrated search.
          required: true
        - label: I used the GitHub search to find a similar question and didn't find it.
          required: true
        - label: I am sure that this is a bug in LangChain rather than my code.
          required: true
        - label: The bug is not resolved by updating to the latest stable version of LangChain (or the specific integration package).
          required: true
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Example Code
      description: |
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.
        
        If a maintainer can copy it, run it, and see it right away, there's a much higher chance that you'll be able to get help.
        
        **Important!** 
        
        * Use code tags (e.g., ```python ... ```) to correctly [format your code](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).
        * INCLUDE the language label (e.g. `python`) after the first three backticks to enable syntax highlighting. (e.g., ```python rather than ```).
        * Reduce your code to the minimum required to reproduce the issue if possible. This makes it much easier for others to help you.
        * Avoid screenshots when possible, as they are hard to read and (more importantly) don't allow others to copy-and-paste your code.
>>>>>>> langchan/master

      placeholder: |
        The following code: 
        
        ```python
        from langchain_core.runnables import RunnableLambda

        def bad_code(inputs) -> int:
          raise NotImplementedError('For demo purpose')
          
          chain = RunnableLambda(bad_code)
          chain.invoke('Hello!')
        ```
  - type: textarea
    id: error
    validations:
      required: false
    attributes:
      label: Error Message and Stack Trace (if applicable)
      description: |
        If you are reporting an error, please include the full error message and stack trace.
      placeholder: |
        Exception + full stack trace
  - type: textarea
    id: description
    attributes:
<<<<<<< HEAD
      label: Дополнительная информация
      description: "Ошибка обнаружена при использовании:"
      options:
        - label: "Официальных примеров (*notebooks*)/скриптов"
        - label: "Собственных или доработанных скриптов"

        Напишите короткое описание того, что вы делаете, какое поведение наблюдаете и какого поведения ожидали.
      placeholder: |
        * Я пытаюсь использовать `gigachain` чтобы сделать X.
        * Я ожидаю получить Y.
        * Вместо этого происходит Z.
=======
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description telling what you are doing, what you expect to happen, and what is currently happening.
      placeholder: |
        * I'm trying to use the `langchain` library to do X.
        * I expect to see Y.
        * Instead, it does Z.
>>>>>>> langchan/master
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
<<<<<<< HEAD
      label: Системная информация
      description: |
        Пожалуйста, поделитесь данными о вашем окружении
        
        "pip freeze | grep gigachain" 
        ОС (windows / linux / mac)
        python version
        
        Если вы используете последние версии gigachain-core, приведите резултат вызова команды:
        
        python -m gigachain_core.sys_info
      placeholder: |
        "pip freeze | grep langchain"
        OC
        python version
        
        Если вы используете последние версии gigachain-core, приведите резултат вызова команды:
        
        python -m langchain_core.sys_info
        
        Команда возвращает пакеты, которые использует GigaChain. При необходимости укажите другие релевантные пакеты.
        Если вы не уверены в том, какие пакеты стоит указывать, можете приложить весь результат команды `pip freeze`.
    validations:
      required: true
  - type: checkboxes
    id: related-components
    attributes:
      label: Компоненты
      description: "По возможности, укажите компоненты библиотеки, к которым относится ошибка:"
      options:
        - label: "LLMs/Chat Models"
        - label: "Embedding Models"
        - label: "Prompts / Prompt Templates / Prompt Selectors"
        - label: "Output Parsers"
        - label: "Document Loaders"
        - label: "Vector Stores / Retrievers"
        - label: "Memory"
        - label: "Agents / Agent Executors"
        - label: "Tools / Toolkits"
        - label: "Chains"
        - label: "Callbacks/Tracing"
        - label: "Async"

  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Воспроизведение ошибки
      description: |
        Предоставьте [образец кода](https://stackoverflow.com/help/minimal-reproducible-example), при выполнении которого возникает ошибка. Подойдет как ссылка на Colab, так и отдельный фрагмент кода.
        По возможности, приложите другие примеры кода, сообщения об ошибках и стек трейсы, которые помогут воспроизвести проблему.
        Обратите внимание на корректное [выделение блоков кода с помощью тегов](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).
        Не нужно присылать скриншоты кода. Такие примеры неудобно читать и их нельзя скопировать.

      placeholder: |
        Опишите шаги для воспроизведения ошибки:

          1.
          2.
          3.

  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: Ожидаемое поведение
      description: "Краткое и понятное описание поведения GigaChain, которого вы ожидали при выполнении кода."
=======
      label: System Info
      description: |
        Please share your system info with us. 
        
        "pip freeze | grep langchain" 
        platform (windows / linux / mac)
        python version
        
        OR if you're on a recent version of langchain-core you can paste the output of:
        
        python -m langchain_core.sys_info
      placeholder: |
        "pip freeze | grep langchain"
        platform
        python version
        
        Alternatively, if you're on a recent version of langchain-core you can paste the output of:
        
        python -m langchain_core.sys_info
        
        These will only surface LangChain packages, don't forget to include any other relevant
        packages you're using (if you're not sure what's relevant, you can paste the entire output of `pip freeze`).
    validations:
      required: true
>>>>>>> langchan/master
