[tool.poetry]
name = "rag-milvus"
version = "0.1.1"
description = "RAG using Milvus"
authors = []
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
gigachain = "^0.1"
gigachain-core = "^0.1"
gigachain-openai = "^0.1"
gigachain-community = "^0.0.30"
pymilvus = "^2.4.3"
scipy = "^1.9"

[tool.poetry.group.dev.dependencies]
gigachain-cli = ">=0.0.4"
fastapi = "^0.104.0"
sse-starlette = "^1.6.5"

[tool.gigaserve]
export_module = "rag_milvus"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "Milvus"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
