[tool.poetry]
name = "rag-lancedb"
version = "0.0.1"
description = "RAG using LanceDB"
authors = ['akash desai']
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<4.0"
<<<<<<< HEAD
gigachain-core = ">=0.1.5"
gigachain-openai = ">=0.0.1"
=======
langchain-core = ">=0.1.5"
langchain-openai = ">=0.0.1"
>>>>>>> langchan/master
lancedb = ">=0.5.5,<1"
openai = "<2"
tiktoken = "^0.5.2"


[tool.poetry.group.dev.dependencies]
<<<<<<< HEAD
gigachain-cli = ">=0.0.21"
=======
langchain-cli = ">=0.0.21"
>>>>>>> langchan/master
fastapi = ">=0.104.0,<1"
sse-starlette = "^1.6.5"

[tool.langserve]
export_module = "rag_lancedb"
export_attr = "chain"

[tool.templates-hub]
use-case = "rag"
author = "LangChain"
integrations = ["OpenAI", "LanceDB"]
tags = ["vectordbs"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
