name: Sync fork repo with upstream
run-name: Sync fork by @${{ github.actor }}

on:
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'dev'

      - name: Set up Git
        run: |
          git config user.email "actions@testmail.com"
          git config user.name "GitHub Actions"


      - name: Sync with upstream
        id: sync
        shell: bash
        run: |
          git fetch
          git checkout -b feature/sync-fork-with-upstream
          git remote add upstream https://github.com/langchain-ai/langchain.git
          git merge -Xtheirs upstream/master
          echo change naming from lingchain to gigachain
          chmod +x ./scripts/fix_naming.sh
          ./scripts/fix_naming.sh <path-to-toml-file>
          echo push changes to feature branch
          git push -u origin feature/sync-fork-with-upstream

      - name: Timestamp
        run: date
