name: Sync fork repo with upstream
run-name: Sync fork by @${{ github.actor }}

on:
  pull_request:
    types: [opened]
    branches:
      - dev
  push:
    branches:
      - feature/*

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: dev
          persist-credentials: false

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/langchain-ai/langchain.git
          git fetch upstream

      - name: Merge changes from upstream
        run: git merge -Xtheirs upstream/master
        continue-on-error: true

      - name: Resolve merge conflicts (if any)
        run: |
          echo "Handle merge conflicts, if any"
          chmod +x ~/work/gigachain/gigachain/.github/scripts/fix_naming.sh
          ~/work/gigachain/gigachain/.github/scripts/fix_naming.sh pyproject.toml

#      - name: Sync with upstream
#        id: sync
#        shell: bash
#        run: |
#          git remote add upstream https://github.com/langchain-ai/langchain.git
#          git fetch upstream
#          git checkout -b feature/sync-fork
#          git merge -Xtheirs upstream/master
#          echo change naming from lingchain to gigachain
#
#          echo push changes to feature branch
#          git push -u origin feature/sync-fork

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          branch: ${{ github.event.pull_request.head.ref }}
          title: Sync fork with upstream changes
          draft: true
          body: Automatically syncing fork repository with upstream changes

      - name: Timestamp
        run: date
