name: Sync with upstream
run-name: Sync by @${{ github.actor }}

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: dev

      - name: Set up Git config
        run: |
          git config --global user.email "github_actions@no-reply.com"
          git config --global user.name "Github actions"

      - name: Fetch upstream changes
        run: |
          git remote add langchan https://github.com/langchain-ai/langchain.git
          git fetch langchan

      - name: Merge changes from upstream
        run: git merge  --allow-unrelated-histories langchan/master

      - name: Resolve .lock conflicts
        run: |
          for file in $(git diff --name-only --diff-filter=U | grep '\.lock$'); do
            git checkout --ours $file
          done
          git add .

      - name: Resolve .toml conflicts
        run: |
          for file in $(git diff --name-only --diff-filter=U | grep '\.toml$'); do
            sed -i '/<<<<<<< HEAD/,/>>>>>>>/d' $file
            sed -i 's/=======//' $file
            git add $file
          done

      - name: Accept incoming changes if not modified in gigachain
        run: |
          git checkout --ours .
          git add .
          git commit -m "Merge langchain/master into gigachain/dev with automated conflict resolution for .toml and .lock files" || echo "No changes to commit"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          base: dev
          branch: "auto-pr-branch"
          title: Sync with upstream changes
          draft: true
          body: Automatically syncing fork repository with upstream changes
        continue-on-error: true

      - name: Echo on error
        if: failure()
        run: |
          echo "Can be some problems with WORKFLOW_TOKEN. It is located in repository secrets(vaild for 90 days). Regenerate it or put there new personal access token."
