name: Sync fork repo with upstream
run-name: Sync fork by @${{ github.actor }}

on:
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: 'feature/sync-fork-with-upstream'

      - name: Sync with upstream
        id: sync
        run: |
          git remote add upstream https://github.com/langchain-ai/langchain.git
          git fetch upstream
          git merge --allow-unrelated-histories -Xtheirs upstream/master
          git push origin feature/sync-fork-with-upstream -f

      - name: Timestamp
        run: date
