name: Sync fork repo with upstream
run-name: Sync fork by @${{ github.actor }}

on:
  workflow_dispatch:
#  pull_request:
#    types: [opened]
#    branches:
#      - dev
#  push:
#    branches:
#      - feature/sync-fork-with-upstream


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: feature/sync-fork-with-upstream

#      - name: Extract git data
#        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Set up Git config
        run: |
          git config --global user.email "no-reply@no-reply.com"
          git config --global user.name "Github actions"

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/langchain-ai/langchain.git
          git fetch upstream

      - name: Merge changes from upstream
        run: git merge -Xtheirs --allow-unrelated-histories upstream/master
        continue-on-error: true

      - name: Fix naming occurred during merge
        run: |
          echo "Handle merge conflicts, if any"
          chmod +x .github/scripts/fix_naming.sh
          .github/scripts/fix_naming.sh pyproject.toml
          git add -A
          git commit -m "fix naming"


      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          base: feature/sync-fork-with-upstream
          branch: "auto-pr-branch"
          title: Sync fork with upstream changes
          draft: true
          body: Automatically syncing fork repository with upstream changes

      - name: Timestamp
        run: date
