name: Sync with upstream
run-name: Sync by @${{ github.actor }}

on: workflow_dispatch

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: dev

      - name: Set up Git config
        run: |
          git config --global user.email "github_actions@no-reply.com"
          git config --global user.name "Github actions"

      - name: Fetch upstream changes
        run: |
          git remote add langchain https://github.com/langchain-ai/langchain.git
          git fetch langchain

      - name: Merge .toml files from langchain/master into gigachain/dev
        run: |
          # Create a temporary branch for the merge
          git checkout -b temp-merge-branch
          
          # Merge only the .toml files
          git checkout langchain/master -- '**/*.toml'
          
          # Handle .toml conflicts
          for file in $(git diff --name-only --diff-filter=U | grep '\.toml$'); do
            # Extract sections with conflicts
            awk '/<<<<<<< HEAD/{flag=1;next}/=======/{flag=0}flag' $file > gigachain_changes.txt
            awk '/=======/{flag=1;next}/>>>>>>>/{flag=0}flag' $file > langchain_changes.txt
            
            # Apply the gigachain naming and langchain version changes
            cp gigachain_changes.txt $file
            sed -i 's/.*version =.*/'$(awk -F ' = ' '/version =/ {print $2}' langchain_changes.txt)'/g' $file
            
            # Clean up temporary files
            rm gigachain_changes.txt langchain_changes.txt
            
            # Add the resolved file to the staging area
            git add $file
          done
    
          # Commit the changes
          git commit -m "Merge .toml files from langchain/master into gigachain/dev with conflict resolution" || echo "No changes to commit"
    
          # Switch back to the dev branch and merge the temporary branch
          git checkout dev
          git merge temp-merge-branch
    
          # Delete the temporary branch
          git branch -d temp-merge-branch

      # - name: Merge changes from upstream
      #   run: git merge  --allow-unrelated-histories langchain/master || true

      # - name: Resolve .lock conflicts
      #   run: |
      #     for file in $(git diff --name-only --diff-filter=U | grep '\.lock$'); do
      #       git checkout --theirs $file
      #     done
      #     git add .

      # - name: Resolve .toml conflicts
      #   run: |
      #     for file in $(git diff --name-only --diff-filter=U | grep '\.toml$'); do
      #       sed -i '/<<<<<<< HEAD/,/>>>>>>>/d' $file
      #       sed -i 's/=======//' $file
      #       git add $file
      #     done

      - name: Accept incoming changes if not modified in gigachain
        run: |
          git checkout --theirs .
          git add .
          git commit -m "Merge langchain/master into gigachain/dev with automated conflict resolution for .toml and .lock files" || echo "No changes to commit"

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          base: dev
          branch: "auto-pr-branch"
          title: Sync with upstream changes
          draft: true
          body: Automatically syncing fork repository with upstream changes
        continue-on-error: true

      - name: Echo on error
        if: failure()
        run: |
          echo "Can be some problems with WORKFLOW_TOKEN. It is located in repository secrets(vaild for 90 days). Regenerate it or put there new personal access token."
