name: Sync fork repo with upstream

on:
  schedule:
    - cron:  '0 12 * * *'

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Sync with upstream
        run: |
          git remote add upstream https://github.com/langchain-ai/langchain.git
          git fetch upstream
          git checkout feature/sync-fork-with-upstream
          git merge -Xours upstream/master
          git push origin feature/sync-fork-with-upstream

      - name: Timestamp
        run: date

      - name: New commits found
        if: steps.sync.outputs.has_new_commits == 'true'
        run: echo "New commits were found to sync."

      - name: No new commits
        if: steps.sync.outputs.has_new_commits == 'false'
        run: echo "There were no new commits."

      - name: Show value of 'has_new_commits'
        run: echo ${{ steps.sync.outputs.has_new_commits }}
