name: Sync fork repo with upstream
run-name: Sync fork by @${{ github.actor }}

on:
  workflow_dispatch:
  pull_request:
    types: [opened]
    branches:
      - dev
  push:
    branches:
      - feature/sync-fork-with-upstream

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: feature/sync-fork-with-upstream

      - name: Set up Git config
        run: |
          git config --global user.email "github_actions@no-reply.com"
          git config --global user.name "Github actions"

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/langchain-ai/langchain.git
          git fetch upstream

      - name: Merge changes from upstream
        run: git merge -Xtheirs --allow-unrelated-histories upstream/master

      - name: Fix naming occurred during merge
        run: |
          echo "Fix naming occurred during merge"
          chmod +x .github/scripts/fix_gigachain_naming.sh
          .github/scripts/fix_gigachain_naming.sh
          git add -A
          git commit -m "fix naming"


      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          base: dev-tmp
          branch: "auto-pr-branch"
          title: Sync fork with upstream changes
          draft: true
          body: Automatically syncing fork repository with upstream changes
        continue-on-error: true

      - name: Custom Error Message
        if: ${{ failure() }}
        run: |
          echo "Can be some problems with personal access token. Check its validity."

      - name: Timestamp
        run: date
