name: Sync fork repo with upstream
run-name: Sync fork by @${{ github.actor }}

on:
  pull_request:
    types: [opened]
    branches:
      - dev

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Extract git data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Set up Git config
        run: |
          git config --global user.email ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}
          git config --global user.name ${{ env.GIT_COMMIT_AUTHOR_NAME }}

      - name: Fetch upstream changes
        run: |
          git remote add upstream https://github.com/langchain-ai/langchain.git
          git fetch upstream

      - name: Merge changes from upstream
        run: git merge -Xtheirs --allow-unrelated-histories upstream/master
        continue-on-error: true

      - name: Resolve merge conflicts (if any)
        run: |
          echo "Handle merge conflicts, if any"
          chmod +x .github/scripts/fix_naming.sh
          .github/scripts/fix_naming.sh pyproject.toml
          git push -u origin ${{ github.event.pull_request.head.ref }}

#      - name: Sync with upstream
#        id: sync
#        shell: bash
#        run: |
#          git remote add upstream https://github.com/langchain-ai/langchain.git
#          git fetch upstream
#          git checkout -b feature/sync-fork
#          git merge -Xtheirs upstream/master
#          echo change naming from lingchain to gigachain
#
#          echo push changes to feature branch
#          git push -u origin feature/sync-fork

#      - name: Create pull request
#        uses: peter-evans/create-pull-request@v3
#        with:
#          token: ${{ secrets.GITHUB_TOKEN }}
#          base: dev
#          branch: "auto-pr-branch"
#          title: Sync fork with upstream changes
#          draft: true
#          body: Automatically syncing fork repository with upstream changes

      - name: Timestamp
        run: date
