name: Upload to Gitverse

on:
  push:
    branches:
      - master
      - feature/*

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          ref: master

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote -v

    - name: Push to Gitverse
      env:
        GITVERSE_TOKEN: ${{ secrets.GITVERSE_PERSONAL_TOKEN }}
      run: |
        git remote add gitverse https://GigaChain_Token:${GITVERSE_TOKEN}@gitverse.ru/sc/pkkashkarov/test.git
        git fetch --unshallow master
        git push -u gitverse --all
        git push -u gitverse --tags
